server:
  port: 8080
spring:
  application:
    name: mycards
  datasource:
    url: jdbc:mysql://localhost:3306/mycards?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
