server:
  port: 8080
spring:
  application:
    name: mycards
  datasource:
    url: jdbc:mysql://192.168.2.6:13306/mycards?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
